## Particle Swarm Optimization


### A function to be optimized is defined 
#### Let's define a function of 3 variables to be optimized
$$ f = f(x_1, x_2, x_3) $$
$$ f = \sin({x_1}^2 + {x_2}^3) + \cos(x_3) $$

In [1]:
import numpy as np

In [2]:
def opt_func(arr):
    # Input: array of size 3
    x = arr[0];
    y = arr[1];
    z = arr[2];
    return np.sin(x**2 + y**3) + np.cos(z)

#### Position of each particle is given by $(x_1, x_2, x_3)$ and how "good" a solution is is defined by $f(x_1, x_2, x_3)$. We can imagine each particle to be a bee, it collects a nectar at position $(x_1, x_2, x_3)$ and the algorithm tells it the value of the nectar

#### The algorithm takes place as follows. There are two "traits" a particle possesses - position $X$ and velocity $V$. Position, undoubtfully, returns $(x_1, x_2, x_3)$ and velocity defines the direction a particle searches next. Suppose at the t-th iteration, a particular particle i has position ${X}^t_i$ and velocity ${V}^t_i$. Then, at the (t+1)-th iteration, the position of that particle is updated as 
$$ X^{t+1}_i = X^t_i + V^t_i $$

#### Unsurprisingly, the velocity of each particle also needs to be updated at each iteration. At each iteration, the global maximum found by the swarm so far is strictly a better local solution. Hence, intuitively, it would be advantageous for every particle of the swarm to incline towards the position of the global best found by the swarm so far.

#### On the other hand, the maximum each particle has found so far is also a strictly better solution than its current position. Therefore, intuitively, it is also advantageous for every particle of the swarm to bend towards the direction of the maximum value this particular particle had found so far.

#### Therefore, let $gbest$ be the coordinate $(x_1, x_2, x_3)$ where global maximum the swarm had found at t-th iteration and ${pbest}_i$ be the coordinate $(x_1, x_2, x_3)$ where the local maximum each particle had found so far. the velocity at (t+1)-th iteration is updated by,
$$ V^{t+1}_i = V^t_i + c_1{r_{1i}}^t(gbest - X^{t}_i) + c_2{r_{2i}}^t({pbest}_i - X^{t}_i) $$

#### The global parameters,  $𝑐_1$   $𝑐_2$ , are learning factors which describe how much a particle in swarm is inclined towards the global maximum the swarm found so far and the local maximum the particle had now reached. According to the tutorial I had read, it is taken to be 2 by default. Each  $𝑟_{1𝑖}$ , $𝑟_{2𝑖}$ are random number from 0 to 1 adding variability to lower the chance of getting stucked in a local solution

In [3]:
c_1 = 2
c_2 = 2
w = 0.4
conv = 1.0e-6

#### The total number of iterations for convergence is taken to be 2000 and the number of particle in the swarm is set to be 20

In [4]:
Iter = 2000
Swarm_size = 50
Dim = 1 #Solution to be within [-50, 50]

#### Swarm is initialized to be an array of dimension (2, 20). The second array in each of the 20 particles denote the maximum searched so far by each of them

In [5]:
def update_gbest(All_swarm, gbest):
    curr_best = gbest;
    for i in range(0, Swarm_size):
        if (opt_func(All_swarm[i]) > opt_func(curr_best)):
            curr_best = All_swarm[i];
    return curr_best;
# A mistake is previously made here

In [6]:
def update_velocity(All_swarm, All_velocity, pbest, gbest):
    All_r_1 = np.random.rand(Swarm_size, 3);
    All_r_2 = np.random.rand(Swarm_size, 3);
    New_velocity = w*All_velocity + c_1*All_r_1*(gbest - All_swarm) + c_2*All_r_2*(pbest - All_swarm);
    return New_velocity;
    

In [7]:
def update_swarm(All_swarm, All_velocity):
    return All_swarm + All_velocity;

In [12]:
def PSO():
    All_swarm = np.random.rand(Swarm_size, 3)*Dim;
    All_velocity = np.zeros((Swarm_size, 3));
    pbest = All_swarm.copy();
    gbest = np.zeros(3);
    for i in range(0, Iter):
        gbest = update_gbest(All_swarm, gbest)
        pbest = (All_swarm >= pbest) * All_swarm + (pbest > All_swarm) * pbest;
        All_velocity = update_velocity(All_swarm, All_velocity, pbest, gbest);
        All_swarm = update_swarm(All_swarm, All_velocity);
        print(gbest, opt_func(gbest))
    return gbest, opt_func(gbest);

In [13]:
PSO()

[0.9832182  0.68522111 0.10866573] 1.954505645864467
[1.12886676 0.69054159 0.02458285] 1.9991590995484918
[1.12886676 0.69054159 0.02458285] 1.9991590995484918
[1.12886676 0.69054159 0.02458285] 1.9991590995484918
[1.12886676 0.69054159 0.02458285] 1.9991590995484918
[1.12886676 0.69054159 0.02458285] 1.9991590995484918
[1.10723047 0.69132114 0.01732235] 1.9997457539716441
[1.10723047 0.69132114 0.01732235] 1.9997457539716441
[1.10723047 0.69132114 0.01732235] 1.9997457539716441
[1.10723047 0.69132114 0.01732235] 1.9997457539716441
[1.10723047 0.69132114 0.01732235] 1.9997457539716441
[1.10723047 0.69132114 0.01732235] 1.9997457539716441
[1.10723047 0.69132114 0.01732235] 1.9997457539716441
[1.10723047 0.69132114 0.01732235] 1.9997457539716441
[1.10723047 0.69132114 0.01732235] 1.9997457539716441
[1.10723047 0.69132114 0.01732235] 1.9997457539716441
[1.10723047 0.69132114 0.01732235] 1.9997457539716441
[1.10723047 0.69132114 0.01732235] 1.9997457539716441
[1.10723047 0.69132114 0.0173

[-3.48183251e+08  1.68426799e+08  1.97221100e+08] 1.9999565934375716
[-3.48183251e+08  1.68426799e+08  1.97221100e+08] 1.9999565934375716
[-3.48183251e+08  1.68426799e+08  1.97221100e+08] 1.9999565934375716
[-3.48183251e+08  1.68426799e+08  1.97221100e+08] 1.9999565934375716
[-3.48183251e+08  1.68426799e+08  1.97221100e+08] 1.9999565934375716
[-3.48183251e+08  1.68426799e+08  1.97221100e+08] 1.9999565934375716
[-3.48183251e+08  1.68426799e+08  1.97221100e+08] 1.9999565934375716
[-3.48183251e+08  1.68426799e+08  1.97221100e+08] 1.9999565934375716
[-3.48183251e+08  1.68426799e+08  1.97221100e+08] 1.9999565934375716
[-3.48183251e+08  1.68426799e+08  1.97221100e+08] 1.9999565934375716
[-3.48183251e+08  1.68426799e+08  1.97221100e+08] 1.9999565934375716
[-3.48183251e+08  1.68426799e+08  1.97221100e+08] 1.9999565934375716
[-3.48183251e+08  1.68426799e+08  1.97221100e+08] 1.9999565934375716
[-3.48183251e+08  1.68426799e+08  1.97221100e+08] 1.9999565934375716
[-3.48183251e+08  1.68426799e+08  

[-3.48183251e+08  1.68426799e+08  1.97221100e+08] 1.9999565934375716
[-3.48183251e+08  1.68426799e+08  1.97221100e+08] 1.9999565934375716
[6.17227611e+24 3.10497753e+21 2.24104325e+27] 1.9999929644818968
[6.17227611e+24 3.10497753e+21 2.24104325e+27] 1.9999929644818968
[6.17227611e+24 3.10497753e+21 2.24104325e+27] 1.9999929644818968
[6.17227611e+24 3.10497753e+21 2.24104325e+27] 1.9999929644818968
[6.17227611e+24 3.10497753e+21 2.24104325e+27] 1.9999929644818968
[6.17227611e+24 3.10497753e+21 2.24104325e+27] 1.9999929644818968
[6.17227611e+24 3.10497753e+21 2.24104325e+27] 1.9999929644818968
[6.17227611e+24 3.10497753e+21 2.24104325e+27] 1.9999929644818968
[6.17227611e+24 3.10497753e+21 2.24104325e+27] 1.9999929644818968
[6.17227611e+24 3.10497753e+21 2.24104325e+27] 1.9999929644818968
[6.17227611e+24 3.10497753e+21 2.24104325e+27] 1.9999929644818968
[6.17227611e+24 3.10497753e+21 2.24104325e+27] 1.9999929644818968
[6.17227611e+24 3.10497753e+21 2.24104325e+27] 1.9999929644818968
[6.1

[6.17227611e+24 3.10497753e+21 2.24104325e+27] 1.9999929644818968
[6.17227611e+24 3.10497753e+21 2.24104325e+27] 1.9999929644818968
[6.17227611e+24 3.10497753e+21 2.24104325e+27] 1.9999929644818968
[6.17227611e+24 3.10497753e+21 2.24104325e+27] 1.9999929644818968
[6.17227611e+24 3.10497753e+21 2.24104325e+27] 1.9999929644818968
[6.17227611e+24 3.10497753e+21 2.24104325e+27] 1.9999929644818968
[6.17227611e+24 3.10497753e+21 2.24104325e+27] 1.9999929644818968
[6.17227611e+24 3.10497753e+21 2.24104325e+27] 1.9999929644818968
[6.17227611e+24 3.10497753e+21 2.24104325e+27] 1.9999929644818968
[6.17227611e+24 3.10497753e+21 2.24104325e+27] 1.9999929644818968
[6.17227611e+24 3.10497753e+21 2.24104325e+27] 1.9999929644818968
[6.17227611e+24 3.10497753e+21 2.24104325e+27] 1.9999929644818968
[6.17227611e+24 3.10497753e+21 2.24104325e+27] 1.9999929644818968
[6.17227611e+24 3.10497753e+21 2.24104325e+27] 1.9999929644818968
[6.17227611e+24 3.10497753e+21 2.24104325e+27] 1.9999929644818968
[6.1722761

[6.17227611e+24 3.10497753e+21 2.24104325e+27] 1.9999929644818968
[6.17227611e+24 3.10497753e+21 2.24104325e+27] 1.9999929644818968
[6.17227611e+24 3.10497753e+21 2.24104325e+27] 1.9999929644818968
[6.17227611e+24 3.10497753e+21 2.24104325e+27] 1.9999929644818968
[6.17227611e+24 3.10497753e+21 2.24104325e+27] 1.9999929644818968
[6.17227611e+24 3.10497753e+21 2.24104325e+27] 1.9999929644818968
[6.17227611e+24 3.10497753e+21 2.24104325e+27] 1.9999929644818968
[6.17227611e+24 3.10497753e+21 2.24104325e+27] 1.9999929644818968
[6.17227611e+24 3.10497753e+21 2.24104325e+27] 1.9999929644818968
[6.17227611e+24 3.10497753e+21 2.24104325e+27] 1.9999929644818968
[6.17227611e+24 3.10497753e+21 2.24104325e+27] 1.9999929644818968
[6.17227611e+24 3.10497753e+21 2.24104325e+27] 1.9999929644818968
[6.17227611e+24 3.10497753e+21 2.24104325e+27] 1.9999929644818968
[6.17227611e+24 3.10497753e+21 2.24104325e+27] 1.9999929644818968
[6.17227611e+24 3.10497753e+21 2.24104325e+27] 1.9999929644818968
[6.1722761

[6.17227611e+24 3.10497753e+21 2.24104325e+27] 1.9999929644818968
[6.17227611e+24 3.10497753e+21 2.24104325e+27] 1.9999929644818968
[6.17227611e+24 3.10497753e+21 2.24104325e+27] 1.9999929644818968
[6.17227611e+24 3.10497753e+21 2.24104325e+27] 1.9999929644818968
[6.17227611e+24 3.10497753e+21 2.24104325e+27] 1.9999929644818968
[6.17227611e+24 3.10497753e+21 2.24104325e+27] 1.9999929644818968
[6.17227611e+24 3.10497753e+21 2.24104325e+27] 1.9999929644818968
[6.17227611e+24 3.10497753e+21 2.24104325e+27] 1.9999929644818968
[6.17227611e+24 3.10497753e+21 2.24104325e+27] 1.9999929644818968
[6.17227611e+24 3.10497753e+21 2.24104325e+27] 1.9999929644818968
[6.17227611e+24 3.10497753e+21 2.24104325e+27] 1.9999929644818968
[6.17227611e+24 3.10497753e+21 2.24104325e+27] 1.9999929644818968
[6.17227611e+24 3.10497753e+21 2.24104325e+27] 1.9999929644818968
[6.17227611e+24 3.10497753e+21 2.24104325e+27] 1.9999929644818968
[6.17227611e+24 3.10497753e+21 2.24104325e+27] 1.9999929644818968
[6.1722761

(array([6.17227611e+24, 3.10497753e+21, 2.24104325e+27]), 1.9999929644818968)

#### Conclusion: Convergence of solution is satisfactory. However, because the solution space is not restricted by a border, search through solution space easily diverges towards an unnecessarily large better local maximum solution. In addition, in this naive implementation, convergence can only be met after the maximum cycles of iteration had been completed. To elaborate on it, in SCF, we declare convergence if the absolute difference between the optimum of t-th iteration and (t+1)-th iteration is less than a threshold value. If a similar criteria is applied on this naive PSO, suppose we had a gbest, in this iteration, no other particles in the swarm had found a better outcome and that the inertial term (w) of the gbest particle is insufficient to create enough deviation larger than the threshold value. We are stucked in a local optimum. Hence, further investigations would be required to improve this naive implementation.